# CMake generated Testfile for 
# Source directory: /home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING
# Build directory: /home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(LAPACK-xlintstd_dtest_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xlintstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dtest.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dtest.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xlintstrfd_dtest_rfp_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xlintstrfd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dtest_rfp.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dtest_rfp.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_nep_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/nep.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dnep.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_sep_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/sep.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dsep.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_svd_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/svd.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dsvd.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dec_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dec.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dec.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_ded_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/ded.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/ded.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dgg_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dgg.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dgg.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dgd_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dgd.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dgd.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dsb_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dsb.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dsb.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dsg_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dsg.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dsg.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dbal_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dbal.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dbal.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dbak_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dbak.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dbak.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dgbal_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dgbal.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dgbal.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dgbak_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dgbak.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dgbak.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_dbb_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/dbb.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dbb.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_glm_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/glm.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dglm.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_gqr_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/gqr.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dgqr.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_gsv_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/gsv.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dgsv.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_csd_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/csd.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dcsd.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK-xeigtstd_lse_in "/usr/bin/cmake" "-DTEST=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/bin/xeigtstd" "-DINPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/lse.in" "-DOUTPUT=/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build/TESTING/dlse.out" "-DINTDIR=." "-P" "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran/TESTING/runtest.cmake")
ADD_TEST(LAPACK_Test_Summary "/usr/bin/python" "lapack_testing.py")
SET_TESTS_PROPERTIES(LAPACK_Test_Summary PROPERTIES  WORKING_DIRECTORY "/home/davincic2/catkin_ws/build_release/cisst_netlib/cisstNetlibLapack/src/cisstNetlib_Fortran-build")
SUBDIRS(MATGEN)
SUBDIRS(LIN)
SUBDIRS(EIG)
