set(_CATKIN_CURRENT_PACKAGE "cisst_conversions")
set(cisst_conversions_VERSION "1.2.0")
set(cisst_conversions_MAINTAINER "Zihan Chen <zihan.chen@jhu.edu>")
set(cisst_conversions_PACKAGE_FORMAT "1")
set(cisst_conversions_BUILD_DEPENDS "roscpp" "kdl_conversions" "tf" "cisst")
set(cisst_conversions_BUILD_EXPORT_DEPENDS "roscpp" "kdl_conversions" "tf" "cisst")
set(cisst_conversions_BUILDTOOL_DEPENDS "catkin")
set(cisst_conversions_BUILDTOOL_EXPORT_DEPENDS )
set(cisst_conversions_EXEC_DEPENDS "roscpp" "kdl_conversions" "tf" "cisst")
set(cisst_conversions_RUN_DEPENDS "roscpp" "kdl_conversions" "tf" "cisst")
set(cisst_conversions_TEST_DEPENDS )
set(cisst_conversions_DOC_DEPENDS )
set(cisst_conversions_DEPRECATED "")