set(_CATKIN_CURRENT_PACKAGE "dvrk_config")
set(dvrk_config_VERSION "1.0.3")
set(dvrk_config_MAINTAINER "Anton Deguet <anton.deguet@jhu.edu>")
set(dvrk_config_PACKAGE_FORMAT "1")
set(dvrk_config_BUILD_DEPENDS )
set(dvrk_config_BUILD_EXPORT_DEPENDS )
set(dvrk_config_BUILDTOOL_DEPENDS "catkin")
set(dvrk_config_BUILDTOOL_EXPORT_DEPENDS )
set(dvrk_config_EXEC_DEPENDS )
set(dvrk_config_RUN_DEPENDS )
set(dvrk_config_TEST_DEPENDS )
set(dvrk_config_DOC_DEPENDS )
set(dvrk_config_DEPRECATED "")