/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */

/*
  Author(s):  Anton Deguet
  Created on: 2014-12-18

  (C) Copyright 2014 Johns Hopkins University (JHU), All Rights Reserved.

--- begin cisst license - do not edit ---

This software is provided "as is" under an open source license, with
no warranty.  The complete license can be found in license.txt and
http://www.cisst.org/cisst/license.txt.

--- end cisst license ---
*/

// file automatically generated by CMake, do not edit!

#pragma once

#ifndef _sawTextToSpeechRevision_h
#define _sawTextToSpeechRevision_h

#define sawTextToSpeech_VERSION_MAJOR 1
#define sawTextToSpeech_VERSION_MINOR 1
#define sawTextToSpeech_VERSION_PATCH 0
#define sawTextToSpeech_VERSION "1.1.0"

#endif // _sawTextToSpeechRevision_h
