#
# Author(s):  Anton Deguet
# Created on: 2011-01-20
#
# (C) Copyright 2011-2016 Johns Hopkins University (JHU), All Rights Reserved.
#

# this file is automatically generated by CMake from
# sawKeyboardConfig.cmake.in

# version numbers
set (sawKeyboard_VERSION_MAJOR "1")
set (sawKeyboard_VERSION_MINOR "1")
set (sawKeyboard_VERSION_PATCH "0")
set (sawKeyboard_VERSION "1.1.0")

# figure out if this file is where it was configured (build tree) or
# not (installed tree)
set (sawKeyboard_CMAKE_CONFIG_FILE "/home/davincic2/catkin_ws/devel_debug/.private/saw_keyboard/share/sawKeyboard/cmake/sawKeyboardConfig.cmake")
get_filename_component (THIS_FILE_PATH
                        ${CMAKE_CURRENT_LIST_FILE}
                        REALPATH)
if ("${sawKeyboard_CMAKE_CONFIG_FILE}" STREQUAL "${THIS_FILE_PATH}")
  # we're using the build directories		
  set (sawKeyboard_INCLUDE_DIR "/home/davincic2/catkin_ws/src/cisst-saw/sawKeyboard/components/include;/home/davincic2/catkin_ws/build_debug/saw_keyboard/include")
  set (sawKeyboard_LIBRARY_DIR "/home/davincic2/catkin_ws/build_debug/saw_keyboard/lib")
else ()
  # try to find the install dir, we know the install is using
  # share/sawKeyboard so we can go ../..
  set (RELATIVE_INSTALL_DIR "${THIS_FILE_PATH}/../..")
  get_filename_component (ABSOLUTE_INSTALL_DIR "${RELATIVE_INSTALL_DIR}" ABSOLUTE)
  # set directories using the install dir
  set (sawKeyboard_INCLUDE_DIR "${ABSOLUTE_INSTALL_DIR}/include")
  set (sawKeyboard_LIBRARY_DIR "${ABSOLUTE_INSTALL_DIR}/lib")
endif ()

set (sawKeyboard_LIBRARIES   "sawKeyboard")
