set(_CATKIN_CURRENT_PACKAGE "cisst_msgs")
set(cisst_msgs_VERSION "1.2.0")
set(cisst_msgs_MAINTAINER "Zihan Chen <zihan.chen@jhu.edu>")
set(cisst_msgs_PACKAGE_FORMAT "1")
set(cisst_msgs_BUILD_DEPENDS "std_msgs" "geometry_msgs" "message_generation")
set(cisst_msgs_BUILD_EXPORT_DEPENDS "std_msgs" "geometry_msgs" "message_runtime")
set(cisst_msgs_BUILDTOOL_DEPENDS "catkin")
set(cisst_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(cisst_msgs_EXEC_DEPENDS "std_msgs" "geometry_msgs" "message_runtime")
set(cisst_msgs_RUN_DEPENDS "std_msgs" "geometry_msgs" "message_runtime")
set(cisst_msgs_TEST_DEPENDS )
set(cisst_msgs_DOC_DEPENDS )
set(cisst_msgs_DEPRECATED "")