/* This file is autogenerated, do not edit*/
#include "moc_vctPlot2DOpenGLQtWidget.cpp"
#include "moc_vctQtWidgetDynamicMatrix.cpp"
#include "moc_vctQtWidgetDynamicVector.cpp"
#include "moc_vctQtWidgetFrame.cpp"
#include "moc_vctQtWidgetFrame4x4.cpp"
#include "moc_vctQtWidgetRotation.cpp"
