// Generated by gencpp from file cisst_msgs/vctDoubleVec.msg
// DO NOT EDIT!


#ifndef CISST_MSGS_MESSAGE_VCTDOUBLEVEC_H
#define CISST_MSGS_MESSAGE_VCTDOUBLEVEC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cisst_msgs
{
template <class ContainerAllocator>
struct vctDoubleVec_
{
  typedef vctDoubleVec_<ContainerAllocator> Type;

  vctDoubleVec_()
    : header()
    , data()  {
    }
  vctDoubleVec_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> const> ConstPtr;

}; // struct vctDoubleVec_

typedef ::cisst_msgs::vctDoubleVec_<std::allocator<void> > vctDoubleVec;

typedef boost::shared_ptr< ::cisst_msgs::vctDoubleVec > vctDoubleVecPtr;
typedef boost::shared_ptr< ::cisst_msgs::vctDoubleVec const> vctDoubleVecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cisst_msgs::vctDoubleVec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cisst_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cisst_msgs': ['/home/davincic2/catkin_ws/src/cisst-saw/cisst-ros/cisst_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb60495edd59d3fcf90e173153ae8a9a";
  }

  static const char* value(const ::cisst_msgs::vctDoubleVec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb60495edd59d3fcULL;
  static const uint64_t static_value2 = 0xf90e173153ae8a9aULL;
};

template<class ContainerAllocator>
struct DataType< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cisst_msgs/vctDoubleVec";
  }

  static const char* value(const ::cisst_msgs::vctDoubleVec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cisst_msgs::vctDoubleVec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vctDoubleVec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cisst_msgs::vctDoubleVec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cisst_msgs::vctDoubleVec_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CISST_MSGS_MESSAGE_VCTDOUBLEVEC_H
