set(_CATKIN_CURRENT_PACKAGE "dvrk_robot")
set(dvrk_robot_VERSION "1.4.0")
set(dvrk_robot_MAINTAINER "Zihan Chen <zihan.chen@jhu.edu>")
set(dvrk_robot_PACKAGE_FORMAT "1")
set(dvrk_robot_BUILD_DEPENDS "saw_intuitive_research_kit" "saw_openigt_link" "cisst_msgs" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(dvrk_robot_BUILD_EXPORT_DEPENDS "saw_intuitive_research_kit" "saw_openigt_link" "cisst_msgs" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(dvrk_robot_BUILDTOOL_DEPENDS "catkin")
set(dvrk_robot_BUILDTOOL_EXPORT_DEPENDS )
set(dvrk_robot_EXEC_DEPENDS "saw_intuitive_research_kit" "saw_openigt_link" "cisst_msgs" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(dvrk_robot_RUN_DEPENDS "saw_intuitive_research_kit" "saw_openigt_link" "cisst_msgs" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(dvrk_robot_TEST_DEPENDS )
set(dvrk_robot_DOC_DEPENDS )
set(dvrk_robot_DEPRECATED "")