blacklist: []
build_space: build_debug
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Debug
devel_layout: linked
devel_space: devel_debug
extend_path: null
install: false
install_space: install_debug
isolate_install: false
jobs_args: []
log_space: logs_debug
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
