set(rqt_dvrk_SETUP_PY_VERSION "0.0.1")
set(rqt_dvrk_SETUP_PY_SCRIPTS "scripts/rqt_dvrk")
set(rqt_dvrk_SETUP_PY_PACKAGES "rqt_dvrk")
set(rqt_dvrk_SETUP_PY_PACKAGE_DIRS "src/rqt_dvrk")
set(rqt_dvrk_SETUP_PY_MODULES "")
set(rqt_dvrk_SETUP_PY_MODULE_DIRS "")