# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cisst_msgs/prmFixtureGainCartesianSet.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class prmFixtureGainCartesianSet(genpy.Message):
  _md5sum = "e52654ad70465afa307bde13463e05e5"
  _type = "cisst_msgs/prmFixtureGainCartesianSet"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

# vf pos & ori
geometry_msgs/Quaternion  ForceOrientation
geometry_msgs/Vector3     ForcePosition
geometry_msgs/Quaternion  TorqueOrientation

# force gains
geometry_msgs/Vector3     PosStiffPos
geometry_msgs/Vector3     PosStiffNeg
geometry_msgs/Vector3     PosDampingPos
geometry_msgs/Vector3     PosDampingNeg
geometry_msgs/Vector3     ForceBiasPos
geometry_msgs/Vector3     ForceBiasNeg

# torque gains
geometry_msgs/Vector3     OriStiffPos
geometry_msgs/Vector3     OriStiffNeg
geometry_msgs/Vector3     OriDampingPos
geometry_msgs/Vector3     OriDampingNeg
geometry_msgs/Vector3     TorqueBiasPos
geometry_msgs/Vector3     TorqueBiasNeg

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','ForceOrientation','ForcePosition','TorqueOrientation','PosStiffPos','PosStiffNeg','PosDampingPos','PosDampingNeg','ForceBiasPos','ForceBiasNeg','OriStiffPos','OriStiffNeg','OriDampingPos','OriDampingNeg','TorqueBiasPos','TorqueBiasNeg']
  _slot_types = ['std_msgs/Header','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ForceOrientation,ForcePosition,TorqueOrientation,PosStiffPos,PosStiffNeg,PosDampingPos,PosDampingNeg,ForceBiasPos,ForceBiasNeg,OriStiffPos,OriStiffNeg,OriDampingPos,OriDampingNeg,TorqueBiasPos,TorqueBiasNeg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(prmFixtureGainCartesianSet, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ForceOrientation is None:
        self.ForceOrientation = geometry_msgs.msg.Quaternion()
      if self.ForcePosition is None:
        self.ForcePosition = geometry_msgs.msg.Vector3()
      if self.TorqueOrientation is None:
        self.TorqueOrientation = geometry_msgs.msg.Quaternion()
      if self.PosStiffPos is None:
        self.PosStiffPos = geometry_msgs.msg.Vector3()
      if self.PosStiffNeg is None:
        self.PosStiffNeg = geometry_msgs.msg.Vector3()
      if self.PosDampingPos is None:
        self.PosDampingPos = geometry_msgs.msg.Vector3()
      if self.PosDampingNeg is None:
        self.PosDampingNeg = geometry_msgs.msg.Vector3()
      if self.ForceBiasPos is None:
        self.ForceBiasPos = geometry_msgs.msg.Vector3()
      if self.ForceBiasNeg is None:
        self.ForceBiasNeg = geometry_msgs.msg.Vector3()
      if self.OriStiffPos is None:
        self.OriStiffPos = geometry_msgs.msg.Vector3()
      if self.OriStiffNeg is None:
        self.OriStiffNeg = geometry_msgs.msg.Vector3()
      if self.OriDampingPos is None:
        self.OriDampingPos = geometry_msgs.msg.Vector3()
      if self.OriDampingNeg is None:
        self.OriDampingNeg = geometry_msgs.msg.Vector3()
      if self.TorqueBiasPos is None:
        self.TorqueBiasPos = geometry_msgs.msg.Vector3()
      if self.TorqueBiasNeg is None:
        self.TorqueBiasNeg = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.ForceOrientation = geometry_msgs.msg.Quaternion()
      self.ForcePosition = geometry_msgs.msg.Vector3()
      self.TorqueOrientation = geometry_msgs.msg.Quaternion()
      self.PosStiffPos = geometry_msgs.msg.Vector3()
      self.PosStiffNeg = geometry_msgs.msg.Vector3()
      self.PosDampingPos = geometry_msgs.msg.Vector3()
      self.PosDampingNeg = geometry_msgs.msg.Vector3()
      self.ForceBiasPos = geometry_msgs.msg.Vector3()
      self.ForceBiasNeg = geometry_msgs.msg.Vector3()
      self.OriStiffPos = geometry_msgs.msg.Vector3()
      self.OriStiffNeg = geometry_msgs.msg.Vector3()
      self.OriDampingPos = geometry_msgs.msg.Vector3()
      self.OriDampingNeg = geometry_msgs.msg.Vector3()
      self.TorqueBiasPos = geometry_msgs.msg.Vector3()
      self.TorqueBiasNeg = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_47d.pack(_x.ForceOrientation.x, _x.ForceOrientation.y, _x.ForceOrientation.z, _x.ForceOrientation.w, _x.ForcePosition.x, _x.ForcePosition.y, _x.ForcePosition.z, _x.TorqueOrientation.x, _x.TorqueOrientation.y, _x.TorqueOrientation.z, _x.TorqueOrientation.w, _x.PosStiffPos.x, _x.PosStiffPos.y, _x.PosStiffPos.z, _x.PosStiffNeg.x, _x.PosStiffNeg.y, _x.PosStiffNeg.z, _x.PosDampingPos.x, _x.PosDampingPos.y, _x.PosDampingPos.z, _x.PosDampingNeg.x, _x.PosDampingNeg.y, _x.PosDampingNeg.z, _x.ForceBiasPos.x, _x.ForceBiasPos.y, _x.ForceBiasPos.z, _x.ForceBiasNeg.x, _x.ForceBiasNeg.y, _x.ForceBiasNeg.z, _x.OriStiffPos.x, _x.OriStiffPos.y, _x.OriStiffPos.z, _x.OriStiffNeg.x, _x.OriStiffNeg.y, _x.OriStiffNeg.z, _x.OriDampingPos.x, _x.OriDampingPos.y, _x.OriDampingPos.z, _x.OriDampingNeg.x, _x.OriDampingNeg.y, _x.OriDampingNeg.z, _x.TorqueBiasPos.x, _x.TorqueBiasPos.y, _x.TorqueBiasPos.z, _x.TorqueBiasNeg.x, _x.TorqueBiasNeg.y, _x.TorqueBiasNeg.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ForceOrientation is None:
        self.ForceOrientation = geometry_msgs.msg.Quaternion()
      if self.ForcePosition is None:
        self.ForcePosition = geometry_msgs.msg.Vector3()
      if self.TorqueOrientation is None:
        self.TorqueOrientation = geometry_msgs.msg.Quaternion()
      if self.PosStiffPos is None:
        self.PosStiffPos = geometry_msgs.msg.Vector3()
      if self.PosStiffNeg is None:
        self.PosStiffNeg = geometry_msgs.msg.Vector3()
      if self.PosDampingPos is None:
        self.PosDampingPos = geometry_msgs.msg.Vector3()
      if self.PosDampingNeg is None:
        self.PosDampingNeg = geometry_msgs.msg.Vector3()
      if self.ForceBiasPos is None:
        self.ForceBiasPos = geometry_msgs.msg.Vector3()
      if self.ForceBiasNeg is None:
        self.ForceBiasNeg = geometry_msgs.msg.Vector3()
      if self.OriStiffPos is None:
        self.OriStiffPos = geometry_msgs.msg.Vector3()
      if self.OriStiffNeg is None:
        self.OriStiffNeg = geometry_msgs.msg.Vector3()
      if self.OriDampingPos is None:
        self.OriDampingPos = geometry_msgs.msg.Vector3()
      if self.OriDampingNeg is None:
        self.OriDampingNeg = geometry_msgs.msg.Vector3()
      if self.TorqueBiasPos is None:
        self.TorqueBiasPos = geometry_msgs.msg.Vector3()
      if self.TorqueBiasNeg is None:
        self.TorqueBiasNeg = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 376
      (_x.ForceOrientation.x, _x.ForceOrientation.y, _x.ForceOrientation.z, _x.ForceOrientation.w, _x.ForcePosition.x, _x.ForcePosition.y, _x.ForcePosition.z, _x.TorqueOrientation.x, _x.TorqueOrientation.y, _x.TorqueOrientation.z, _x.TorqueOrientation.w, _x.PosStiffPos.x, _x.PosStiffPos.y, _x.PosStiffPos.z, _x.PosStiffNeg.x, _x.PosStiffNeg.y, _x.PosStiffNeg.z, _x.PosDampingPos.x, _x.PosDampingPos.y, _x.PosDampingPos.z, _x.PosDampingNeg.x, _x.PosDampingNeg.y, _x.PosDampingNeg.z, _x.ForceBiasPos.x, _x.ForceBiasPos.y, _x.ForceBiasPos.z, _x.ForceBiasNeg.x, _x.ForceBiasNeg.y, _x.ForceBiasNeg.z, _x.OriStiffPos.x, _x.OriStiffPos.y, _x.OriStiffPos.z, _x.OriStiffNeg.x, _x.OriStiffNeg.y, _x.OriStiffNeg.z, _x.OriDampingPos.x, _x.OriDampingPos.y, _x.OriDampingPos.z, _x.OriDampingNeg.x, _x.OriDampingNeg.y, _x.OriDampingNeg.z, _x.TorqueBiasPos.x, _x.TorqueBiasPos.y, _x.TorqueBiasPos.z, _x.TorqueBiasNeg.x, _x.TorqueBiasNeg.y, _x.TorqueBiasNeg.z,) = _struct_47d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_47d.pack(_x.ForceOrientation.x, _x.ForceOrientation.y, _x.ForceOrientation.z, _x.ForceOrientation.w, _x.ForcePosition.x, _x.ForcePosition.y, _x.ForcePosition.z, _x.TorqueOrientation.x, _x.TorqueOrientation.y, _x.TorqueOrientation.z, _x.TorqueOrientation.w, _x.PosStiffPos.x, _x.PosStiffPos.y, _x.PosStiffPos.z, _x.PosStiffNeg.x, _x.PosStiffNeg.y, _x.PosStiffNeg.z, _x.PosDampingPos.x, _x.PosDampingPos.y, _x.PosDampingPos.z, _x.PosDampingNeg.x, _x.PosDampingNeg.y, _x.PosDampingNeg.z, _x.ForceBiasPos.x, _x.ForceBiasPos.y, _x.ForceBiasPos.z, _x.ForceBiasNeg.x, _x.ForceBiasNeg.y, _x.ForceBiasNeg.z, _x.OriStiffPos.x, _x.OriStiffPos.y, _x.OriStiffPos.z, _x.OriStiffNeg.x, _x.OriStiffNeg.y, _x.OriStiffNeg.z, _x.OriDampingPos.x, _x.OriDampingPos.y, _x.OriDampingPos.z, _x.OriDampingNeg.x, _x.OriDampingNeg.y, _x.OriDampingNeg.z, _x.TorqueBiasPos.x, _x.TorqueBiasPos.y, _x.TorqueBiasPos.z, _x.TorqueBiasNeg.x, _x.TorqueBiasNeg.y, _x.TorqueBiasNeg.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ForceOrientation is None:
        self.ForceOrientation = geometry_msgs.msg.Quaternion()
      if self.ForcePosition is None:
        self.ForcePosition = geometry_msgs.msg.Vector3()
      if self.TorqueOrientation is None:
        self.TorqueOrientation = geometry_msgs.msg.Quaternion()
      if self.PosStiffPos is None:
        self.PosStiffPos = geometry_msgs.msg.Vector3()
      if self.PosStiffNeg is None:
        self.PosStiffNeg = geometry_msgs.msg.Vector3()
      if self.PosDampingPos is None:
        self.PosDampingPos = geometry_msgs.msg.Vector3()
      if self.PosDampingNeg is None:
        self.PosDampingNeg = geometry_msgs.msg.Vector3()
      if self.ForceBiasPos is None:
        self.ForceBiasPos = geometry_msgs.msg.Vector3()
      if self.ForceBiasNeg is None:
        self.ForceBiasNeg = geometry_msgs.msg.Vector3()
      if self.OriStiffPos is None:
        self.OriStiffPos = geometry_msgs.msg.Vector3()
      if self.OriStiffNeg is None:
        self.OriStiffNeg = geometry_msgs.msg.Vector3()
      if self.OriDampingPos is None:
        self.OriDampingPos = geometry_msgs.msg.Vector3()
      if self.OriDampingNeg is None:
        self.OriDampingNeg = geometry_msgs.msg.Vector3()
      if self.TorqueBiasPos is None:
        self.TorqueBiasPos = geometry_msgs.msg.Vector3()
      if self.TorqueBiasNeg is None:
        self.TorqueBiasNeg = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 376
      (_x.ForceOrientation.x, _x.ForceOrientation.y, _x.ForceOrientation.z, _x.ForceOrientation.w, _x.ForcePosition.x, _x.ForcePosition.y, _x.ForcePosition.z, _x.TorqueOrientation.x, _x.TorqueOrientation.y, _x.TorqueOrientation.z, _x.TorqueOrientation.w, _x.PosStiffPos.x, _x.PosStiffPos.y, _x.PosStiffPos.z, _x.PosStiffNeg.x, _x.PosStiffNeg.y, _x.PosStiffNeg.z, _x.PosDampingPos.x, _x.PosDampingPos.y, _x.PosDampingPos.z, _x.PosDampingNeg.x, _x.PosDampingNeg.y, _x.PosDampingNeg.z, _x.ForceBiasPos.x, _x.ForceBiasPos.y, _x.ForceBiasPos.z, _x.ForceBiasNeg.x, _x.ForceBiasNeg.y, _x.ForceBiasNeg.z, _x.OriStiffPos.x, _x.OriStiffPos.y, _x.OriStiffPos.z, _x.OriStiffNeg.x, _x.OriStiffNeg.y, _x.OriStiffNeg.z, _x.OriDampingPos.x, _x.OriDampingPos.y, _x.OriDampingPos.z, _x.OriDampingNeg.x, _x.OriDampingNeg.y, _x.OriDampingNeg.z, _x.TorqueBiasPos.x, _x.TorqueBiasPos.y, _x.TorqueBiasPos.z, _x.TorqueBiasNeg.x, _x.TorqueBiasNeg.y, _x.TorqueBiasNeg.z,) = _struct_47d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_47d = struct.Struct("<47d")
