set(_CATKIN_CURRENT_PACKAGE "cisst_ros_bridge")
set(cisst_ros_bridge_VERSION "1.2.0")
set(cisst_ros_bridge_MAINTAINER "Zihan Chen <zihan.chen@jhu.edu>")
set(cisst_ros_bridge_PACKAGE_FORMAT "1")
set(cisst_ros_bridge_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cisst_msgs" "cisst")
set(cisst_ros_bridge_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cisst_msgs" "cisst")
set(cisst_ros_bridge_BUILDTOOL_DEPENDS "catkin")
set(cisst_ros_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(cisst_ros_bridge_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cisst_msgs" "cisst")
set(cisst_ros_bridge_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cisst_msgs" "cisst")
set(cisst_ros_bridge_TEST_DEPENDS )
set(cisst_ros_bridge_DOC_DEPENDS )
set(cisst_ros_bridge_DEPRECATED "")