/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */

/*
  (C) Copyright 2016 Johns Hopkins University (JHU), All Rights Reserved.

--- begin cisst license - do not edit ---

This software is provided "as is" under an open source license, with
no warranty.  The complete license can be found in license.txt and
http://www.cisst.org/cisst/license.txt.

--- end cisst license ---
*/

// file automatically generated by CMake, do not edit!

#pragma once

#ifndef _sawOptoforceSensorRevision_h
#define _sawOptoforceSensorRevision_h

#define sawOptoforceSensor_VERSION_MAJOR 1
#define sawOptoforceSensor_VERSION_MINOR 0
#define sawOptoforceSensor_VERSION_PATCH 0
#define sawOptoforceSensor_VERSION "1.0.0"

#endif // _sawOptoforceSensorRevision_h
