set(_CATKIN_CURRENT_PACKAGE "optoforce_ros")
set(optoforce_ros_VERSION "1.0.0")
set(optoforce_ros_MAINTAINER "Anton Deguet <anton.deguet@jhu.edu>")
set(optoforce_ros_PACKAGE_FORMAT "1")
set(optoforce_ros_BUILD_DEPENDS "saw_optoforce_sensor" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(optoforce_ros_BUILD_EXPORT_DEPENDS "saw_optoforce_sensor" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(optoforce_ros_BUILDTOOL_DEPENDS "catkin")
set(optoforce_ros_BUILDTOOL_EXPORT_DEPENDS )
set(optoforce_ros_EXEC_DEPENDS "saw_optoforce_sensor" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(optoforce_ros_RUN_DEPENDS "saw_optoforce_sensor" "cisst_ros_bridge" "geometry_msgs" "roscpp" "std_msgs" "roslib")
set(optoforce_ros_TEST_DEPENDS )
set(optoforce_ros_DOC_DEPENDS )
set(optoforce_ros_DEPRECATED "")