#
# Author(s):  Peter Kazanzides
# Created on: 2016-06-10
#
# (C) Copyright 2016 Johns Hopkins University (JHU), All Rights Reserved.
#

# this file is automatically generated by CMake from
# sawOptoforceSensorConfig.cmake.in

# version numbers
set (sawOptoforceSensor_VERSION_MAJOR "1")
set (sawOptoforceSensor_VERSION_MINOR "0")
set (sawOptoforceSensor_VERSION_PATCH "0")
set (sawOptoforceSensor_VERSION "1.0.0")

# figure out if this file is where it was configured (build tree) or
# not (installed tree)
set (sawOptoforceSensor_CMAKE_CONFIG_FILE "/home/davincic2/catkin_ws/devel_debug/.private/saw_optoforce_sensor/share/sawOptoforceSensor/cmake/sawOptoforceSensorConfig.cmake")
get_filename_component (THIS_FILE_PATH
                        ${CMAKE_CURRENT_LIST_FILE}
                        REALPATH)
if (WIN32)
  # Fix for Windows
  string(TOLOWER "${sawOptoforceSensor_CMAKE_CONFIG_FILE}" sawOptoforceSensor_CMAKE_CONFIG_FILE)
  string(TOLOWER "${THIS_FILE_PATH}" THIS_FILE_PATH)
endif (WIN32)

if ("${sawOptoforceSensor_CMAKE_CONFIG_FILE}" STREQUAL "${THIS_FILE_PATH}")
  # we're using the build directories
  set (sawOptoforceSensor_INCLUDE_DIR "/home/davincic2/catkin_ws/src/cisst-saw/sawOptoforceSensor/components/include;/home/davincic2/catkin_ws/build_debug/saw_optoforce_sensor/include")
  set (sawOptoforceSensor_LIBRARY_DIR "/home/davincic2/catkin_ws/build_debug/saw_optoforce_sensor/lib")
else ()
  # try to find the install dir, we know the install is using
  # share/sawOptoforceSensor so we can go ../..
  set (RELATIVE_INSTALL_DIR "${THIS_FILE_PATH}/../..")
  get_filename_component (ABSOLUTE_INSTALL_DIR "${RELATIVE_INSTALL_DIR}" ABSOLUTE)
  # set directories using the install dir
  set (sawOptoforceSensor_INCLUDE_DIR "${ABSOLUTE_INSTALL_DIR}/include")
  set (sawOptoforceSensor_LIBRARY_DIR "${ABSOLUTE_INSTALL_DIR}/lib")
endif ()

set (sawOptoforceSensor_LIBRARIES   "sawOptoforceSensor")
