set(_CATKIN_CURRENT_PACKAGE "dvrk_python")
set(dvrk_python_VERSION "1.4.0")
set(dvrk_python_MAINTAINER "Anton Deguet <anton.deguet@jhu.edu>")
set(dvrk_python_PACKAGE_FORMAT "1")
set(dvrk_python_BUILD_DEPENDS "rospy")
set(dvrk_python_BUILD_EXPORT_DEPENDS "rospy")
set(dvrk_python_BUILDTOOL_DEPENDS "catkin")
set(dvrk_python_BUILDTOOL_EXPORT_DEPENDS )
set(dvrk_python_EXEC_DEPENDS "rospy")
set(dvrk_python_RUN_DEPENDS "rospy")
set(dvrk_python_TEST_DEPENDS )
set(dvrk_python_DOC_DEPENDS )
set(dvrk_python_DEPRECATED "")