#
# Author(s):  Anton Deguet
# Created on: 2013-05-15
#
# (C) Copyright 2013-2016 Johns Hopkins University (JHU), All Rights Reserved.
#

# this file is automatically generated by CMake from
# sawTextToSpeechConfig.cmake.in

set (sawTextToSpeech_VERSION_MAJOR "1")
set (sawTextToSpeech_VERSION_MINOR "1")
set (sawTextToSpeech_VERSION_PATCH "0")
set (sawTextToSpeech_VERSION "1.1.0")

# figure out if this file is where it was configured (build tree) or
# not (installed tree)
set (sawTextToSpeech_CMAKE_CONFIG_FILE "/home/davincic2/catkin_ws/devel_debug/.private/saw_text_to_speech/share/sawTextToSpeech/cmake/sawTextToSpeechConfig.cmake")
get_filename_component (THIS_FILE_PATH
                        ${CMAKE_CURRENT_LIST_FILE}
                        REALPATH)

if ("${sawTextToSpeech_CMAKE_CONFIG_FILE}" STREQUAL "${THIS_FILE_PATH}")
  # we're using the build directories
  set (sawTextToSpeech_INCLUDE_DIR "/home/davincic2/catkin_ws/src/cisst-saw/sawTextToSpeech/components/include;/home/davincic2/catkin_ws/build_debug/saw_text_to_speech/include")
  set (sawTextToSpeech_LIBRARY_DIR "/home/davincic2/catkin_ws/build_debug/saw_text_to_speech/lib")
else ()
  # try to find the install dir, we know the install is using
  # share/sawTextToSpeech so we can go ../..
  set (RELATIVE_INSTALL_DIR "${THIS_FILE_PATH}/../..")
  get_filename_component (ABSOLUTE_INSTALL_DIR "${RELATIVE_INSTALL_DIR}" ABSOLUTE)
  # set directories using the install dir
  set (sawTextToSpeech_INCLUDE_DIR "${ABSOLUTE_INSTALL_DIR}/include")
  set (sawTextToSpeech_LIBRARY_DIR "${ABSOLUTE_INSTALL_DIR}/lib")
endif ()

set (sawTextToSpeech_LIBRARIES   "sawTextToSpeech")
